name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up .NET Core SDK
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x' # Use the version you need

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build the application
    - name: Build the application
      run: dotnet build --configuration Release

    # Publish the application (for a web app or console app, adjust accordingly)
    - name: Publish the application
      run: dotnet publish -c Release -o ./publish

    # Compress the published output
    - name: Zip the build
      run: zip -r ./build.zip ./publish

    # Upload the zipped build as an artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: ./build.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install GitHub CLI (gh)
      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      # Download the zipped build artifact
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build

      # Create a GitHub release using gh CLI
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract the tag name from the GitHub reference
          TAG_NAME=${GITHUB_REF#refs/tags/}
          
          # Create the release
          gh release create $TAG_NAME build.zip --title "Release $TAG_NAME" --notes "Build from tag $TAG_NAME" --latest
